version: '3.8'

services:
  icf-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3000"
      - "5000:5000"
    volumes:
      - uploads:/app/public/uploads
      - results:/app/public/results
    environment:
      - NODE_ENV=production
      - CONTAINERIZED=true
      - NON_INTERACTIVE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}

volumes:
  uploads:
  results:
