version: '3.8'

services:
  icf-frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3010:3000"
    volumes:
      - uploads:/app/public/uploads
      - results:/app/public/results
    depends_on:
      - icf-backend
    environment:
      - NODE_ENV=production
      - CONTAINERIZED=true
      - BACKEND_API_URL=http://icf-backend:5000

  icf-backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - uploads:/app/public/uploads
      - results:/app/public/results
    environment:
      - NON_INTERACTIVE=true
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}

volumes:
  uploads:
  results:
