version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/public/uploads
      - results:/app/public/results
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
      - CONTAINERIZED=true
      - BACKEND_API_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - uploads:/app/public/uploads
      - results:/app/public/results
    environment:
      - NON_INTERACTIVE=true

volumes:
  uploads:
  results:
